name: Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create SSH key and Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

        shell: bash
        
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Deploy with SSH
        run: ssh -i $SSH_KEY_PATH $SSH_HOST 'cd compose; ./blog_update.sh'
        env:
          SSH_KEY_PATH: ../private.key
          SSH_HOST: ${{secrets.SSH_HOST}}